language: c

env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
  global:
    - SETUP_XVFB=True
    - CONDA_CHANNELS=conda-forge
    - CONDA_DEPENDENCIES="numpy scipy astropy matplotlib pytest coverage"
    - PIP_DEPENDENCIES="coverage coveralls pytest-cov"

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - py.test --cov sedfitter sedfitter

after_success:
    - coveralls
